org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
authToken=jp_9lured1djkqj83p7vaqhes4img
aws_access_key=AKIAXB3KY4F5AQJD6WHT
aws_secret_pass=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
android.enableDexingArtifactTransform=false

# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator

android.newDsl=false
